### ISSUE TITLE
Window freezing

### ISSUE THREAD

**Issue by JerryImMouse** [Tornado-Technology/hypercube#6]
If you ill minimize window and wait for about 1 minute, window will maximize behind all active windows, if you'll try to click on it you its process will be finished immediately
![image](https://github.com/Tornado-Technology/hypercube/assets/48524572/45c4f28c-ed94-46c5-8d3f-159ab83cc117)

Unfortunately, RenderDoc showed nothing, logs did the same

**Comment by Tornado-Technology** [comment]
As testing has shown the window gets stuck in the resize mode and stops responding to events. Most likely, it is something with the work of these methods GLFW or rendering.

**Comment by JerryImMouse** [comment]
you mean glfw window methods?

**Comment by JerryImMouse** [comment]
Found that title changing frezzed too

**Comment by Tornado-Technology** [comment]
![image](https://github.com/user-attachments/assets/1e0adbcb-a215-4ecc-bbec-1586f80a194d)
`Exception of type 'System.ExecutionEngineException' was thrown.`

**Comment by Tornado-Technology** [comment]
Okay I find reasone -> https://github.com/opentk/opentk/issues/1073
GC collect GLFW callbacks

**Comment by JerryImMouse** [comment]
Probably fixed, but
![image](https://github.com/user-attachments/assets/a35f8101-cf96-46a2-8a11-cd5b6aabddfc)

Happened when i was "flying" with camera, ill look on it better so i could determine if it linked to this

**Comment by JerryImMouse** [comment]
Yeah, this one is linked, but ill open another issue
